title: MetaPerson 2.0 UE
description: This project demonstrates how to create and use MetaPerson avatars with Epic animations.
theme: just-the-docs

url: https://github.com/itseez3d/metaperson-ue-docs


