title: MetaPerson 2.0 UE
description: This project demonstrates how to create and use MetaPerson avatars with Epic animations.
remote_theme: pmarsceill/just-the-docs

url: https://ue-docs.metaperson.avatarsdk.com/



